USE [master]
GO

CREATE DATABASE [sample]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sample', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\sample.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sample_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\sample_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [sample] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sample].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sample] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sample] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sample] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sample] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sample] SET ARITHABORT OFF 
GO

ALTER DATABASE [sample] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sample] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sample] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sample] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sample] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sample] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sample] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sample] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sample] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sample] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sample] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sample] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sample] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sample] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sample] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sample] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sample] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sample] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [sample] SET  MULTI_USER 
GO

ALTER DATABASE [sample] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sample] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sample] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sample] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [sample] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sample] SET QUERY_STORE = OFF
GO

USE [sample]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [sample] SET  READ_WRITE 
GO

